### ISSUE TITLE
Adding code

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlasPipeline/abakit#1]
@qobilidop @Junjie-Cheng 

This package needs to be filled up and documented with the code and methods in PROCECC.md:
https://github.com/eddyod/pipeline_utility/blob/master/PROCESS.md

Look for the create_XXX.py scripts and take the methods that they use and put them here.

**Comment by qobilidop** [comment]
Hi Ed,

I've been thinking about this and reading the pipeline scripts for a while. I have some thoughts about the general design of this package. But since I'm less familiar with the pipeline and other backgrounds, I would like to discuss with you and Junjie before committing code:

- For the scope of this package, I think it should contain some stable tools for the pipeline to use including data object abstractions, common algorithms, and wrappers to other useful tools like Neuroglancer and SimpleITK. The actual pipeline scripts would use the tools from this package and talk with the database to do the real work.
- One reason to make this separation is to make the package more stable. The pipeline logic is up to faster changes. For example, there could be multiple methods to do alignments, and we might be switching between them back and forth as the project moves forward.
- The second reason to make this separation is to have a clear boundary between the general tools and the database. I feel the tools we provided here should be usable even without the database. This allows for easier and safer experimentation and testing. It's safer because we don't need to worry about accidentally modifying the database in unwanted ways.
- Also, I think we should prepare a suite of testing data. My rough idea is to prepare a small size test data for this package and set up CIs to do continuous testing (and potentially continuous benchmarking). Then a real large size testing could be run on the pipeline side and don't have to be continuous.

**Comment by eddyod** [comment]
@qobilidop 
Here are some methods from the pipeline_utility that could be added to the abakit.
from utilities.utilities_mask import fix_with_fill, fix_thionin, trim_edges, create_mask_pass1
from utilities.utilities_mask import rotate_image, place_image, scaled, equalized
from utilities.utilities_process import workernoshell, workershell, test_dir
